### ISSUE TITLE
the problem with the dead message policy

### ISSUE THREAD

**Issue by SatoruFF** [kffl/bunny-rest-proxy#210]
hello, I ran into such a problem that when specifying a dead message policy, I get this error(I saw a message in the documentation that the library is not fully ready yet, was this meant):

/app/build/subscriber/retry-manager.js:18
2023-09-11 17:57:48 this.logger.warn(`Exceeded the maximum number of delivery attempts for the message ID: ${msg.properties.messageId}, ${this.deadLetterPolicy.descripeBehavior} message`);
2023-09-11 17:57:48 ^
2023-09-11 17:57:48
2023-09-11 17:57:48 TypeError: Unable to read undefined properties (reading 'descripeBehavior')

Could this be a problem related to incorrect configuration file configuration? Here is my configuration.yml

---
publishers:
- queueName: json-queue
Content Type: json
- Queue name: my_queue
Content Type: json
  - queueName: dead
    contentType: json
- Queue name: binary queue
Content type: binary
consumers:
- queueName: json-queue
- Queue name: my_queue
- Queue name: binary queue
- Queue name: dead 
- subscribers:
- queueName: json queue
purpose: http://host.docker.internal:8001/subscribe
preliminary selection: 2
Retreat strategy: constant
attempts: 2
Repeated delay: 1000
- queueName: json queue
purpose: http://host.docker.internal:8002/subscribe
preliminary selection: 2
Retreat strategy: constant
attempts: 2
Repeated delay: 1000
- queueName: json queue
purpose: http://host.docker.internal:8003/subscribe
preliminary selection: 2
Retreat strategy: constant
attempts: 2
Repeated delay: 1000
deadLetterPolicy: dql
deadLetterQueueName: dead

**Comment by kffl** [comment]
Resolved in #211
